#!/usr/bin/env python
##############################################################################
#
# diffpy.utils      by DANSE Diffraction group
#                   Simon J. L. Billinge
#                   (c) 2010 Trustees of the Columbia University
#                   in the City of New York.  All rights reserved.
#
# File coded by:    Timur Dykhne, Chris Farrow, Pavol Juhas
#
# See AUTHORS.txt for a list of people who contributed.
# See LICENSE.txt for license information.
#
##############################################################################

# Turn on the "with" statement for Python 2.5.
from __future__ import with_statement

# module version
__id__ = "$Id$"


def loadData(filename, minrows=10, mincols=1, **kwargs):
    """Find and load data from a text file.

    The data reading starts at the first matrix block of at least minrows rows
    and mincols columns.  This seems to work for most of the datafiles
    including those generated by PDFGetX2.

    filename -- name of the file we want to load data from.
    minrows  -- minimum number of rows in the first data block.
                All rows must have the same number of floating point values.
    mincols  -- minimum number of floats in a data block.  If usecols is
                defined, only the specified columns are checked for floats.
    usecols  -- zero-based index of columns to be loaded, by default use
                all detected columns.
    unpack   -- return data as a sequence of columns that allows tuple
                unpacking such as  x, y = loadData(FILENAME, unpack=True).
                Note transposing the loaded array as loadData(FILENAME).T
                has the same effect.
    kwargs   -- keyword arguments that are passed to numpy.loadtxt

    Return a numpy array of the data.
    See also numpy.loadtxt for more details.
    """
    from numpy import array, loadtxt
    # determine the arguments
    delimiter = kwargs.get('delimiter')
    usecols = kwargs.get('usecols')
    # Check if a line consists of floats only and return their count
    # Return zero if some strings cannot be converted.
    def countfloats(line):
        try:
            words = line.split(delimiter)
            if usecols is not None:
                words = [words[i] for i in usecols]
            else:
                # remove trailing blank columns
                while words and not words[-1].strip():
                    words.pop(-1)
            nf = len(map(float, words))
        except (IndexError, ValueError):
            nf = 0
        return nf
    # make sure fid gets cleaned up
    with open(filename, 'rb') as fid:
        # search for the start of datablock
        start = ncols = None
        fpos = nrows = 0
        for line in fid:
            fpos += len(line)
            nc = countfloats(line)
            if nc < mincols:
                start = None
                continue
            # nc is acceptable here, require the same number of columns
            # throughout the datablock
            if start is None or nc != ncols:
                ncols = nc
                nrows = 0
                start = fpos - len(line)
            nrows += 1
            # block was found here!
            if nrows >= minrows:
                break
        # Return an empty array when no data found.
        # loadtxt would otherwise raise an exception on loading from EOF.
        if start is None:
            rv = array([], dtype=float)
        else:
            fid.seek(start)
            # always use usecols argument so that loadtxt does not crash
            # in case of trailing delimiters.
            kwargs.setdefault('usecols', range(ncols))
            rv = loadtxt(fid, **kwargs)
    return rv

# End of file
